from boxcomtools.types import Path as _Path, BoxFolder, BoxFile, BoxClient

try:
    # Even though there is no "../_version" file,
    # it should be generated by
    # setuptools_scm when building the package
    from seaborn_extensions._version import __version__

    version = __version__
except ImportError:
    from setuptools_scm import get_version as _get_version

    version = __version__ = _get_version(root="..", relative_to=__file__)

__author__ = """Andre Rendeiro"""
__email__ = "afrendeiro@gmail.com"


SECRET_FILE = _Path("~/.imctransfer.auth.json").expanduser().absolute()
APP_REDIRECT_URL = "https://imctransfer.herokuapp.com/"
